use_frameworks!

target 'TextkitMarkdown_Example' do
  pod 'TextkitMarkdown', :path => '../'

  target 'TextkitMarkdown_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
